### ISSUE TITLE
在Google Play上找不到，自己又不会编译。

### ISSUE THREAD

**Issue by ghost** [cmeng-git/hymnchtv#3]
在Google Play上找不到，自己又不会编译。咋个办？1.72在哪里可以下载的到？

**Comment by cmeng-git** [comment]
see https://github.com/cmeng-git/hymnchtv/issues/2#issuecomment-1030625109

**Comment by cmeng-git** [comment]
see https://github.com/cmeng-git/hymnchtv/releases
