### ISSUE TITLE
今天刚下载安装，希望弟兄能够添加上青年诗歌

### ISSUE THREAD

**Issue by Whys8182** [cmeng-git/hymnchtv#4]
今天刚下载安装，希望弟兄能够添加上青年诗歌

**Comment by cmeng-git** [comment]
Are all the songs in 青年诗歌 unique, or many of them are actually from other hynms collections?

If not all are unique, are you able to provide me a list of the unique 青年诗歌 number.
If possible provide me a translation table between 青年诗歌 number and other collection hymn number e.g

yb0001 : bb0876
yb0010:  bb0837

Need to have this info before any decision can be made.

// =============
青年诗歌中的所有歌曲都是独一无二的，还是其中许多歌曲实际上来自其他诗集？

如果不是全部都是唯一的，您能给我提供一份唯一的青年作品编号列表吗？
如果可能的话，请给我一份青年诗歌编号和其他收藏赞美诗编号之间的翻译表，例如

yb0001：bb0876
yb0010 : bb0837

在做出任何决定之前需要获得此信息。

**Comment by cmeng-git** [comment]
有谁愿意帮助生成青年诗歌的对照表参考文件，格式与给定的相同。我需要这个文件来实现新的功能。

^ 0001: 神就是爱 #bb876
^ 0002: 真爱 #bb847
^ 0003: 遇见你们 #bb751
^ 0004: 陪我生活 #bb842
^ 0005: 第一声呼声 #bb841
^ 0006: 我们同来在一起 #xb110
^ 0007: 我们是一家人 #xb022
^ 0008: 兴起 #xb1
^ 0009: 这是你我的聚集 #xb17
^ 0010: 信的故事 #bb837
^ 0011: 只要借着信 #xb72
^ 0012: 大好信息 #bb840
^ 0013: 爱使我们相聚一起 #bb752
^ 0014: 云彩 #bb839
^ 0015: 活神的家 #bb843
^ 0016: 神圣罗曼史 #bb328
^ 0017: 惟见荣耀里的基督 #bb329
^ 0018: 耶稣！我爱你 #bb301
^ 0019: 主阿，我爱你 #yb19
^ 0020: 主阿，我爱你 #db327
^ 0021: 箭之歌 #yb21

[toc_youth2hymn.txt](https://github.com/cmeng-git/hymnchtv/files/12340788/toc_youth2hymn.txt)

**Comment by Whys8182** [comment]
#符号后面是什么意思？

**Comment by cmeng-git** [comment]
#xxx 表示对应的诗歌，与青年诗歌曲相同。

#bb837 => 补充本 837，与青年诗歌曲#10相同
#db327 => 大本诗歌 327，与青年诗歌曲#20相同

其他例子：
#xb => 新歌颂咏 
#er => 儿童诗歌

#yb21 => 青年诗歌编号#21，没有对应的诗歌
对于这种类，我需要创建实际的显示内容。

对于那些愿意提供帮助的人，以下英语到中文索引文件可能有助于生成所需的交叉引用索引文件。首先检查诗歌的标题，找到后检查其内容并验证是否与青年诗歌相符。一旦匹配，就可以使用该记录。
[toc_all_eng2ch.txt](https://github.com/cmeng-git/hymnchtv/files/12353674/toc_all_eng2ch.txt)

**Comment by cmeng-git** [comment]
Issue closed with no community support.
