### ISSUE TITLE
希望可以增加对每一首诗歌添加注解的机制

### ISSUE THREAD

**Issue by stevenyi1760** [cmeng-git/hymnchtv#5]
1.增加对诗歌添加注解的机制，或是可以像电子圣经里的书签一样。
2.类似可以对每一首诗歌做一些记号，以此表示我对这首诗歌的摸着。

**Comment by cmeng-git** [comment]
Your request is outside the original design scope of the app; feel not many user will need this feature. Sorry unable to entertain.
