### ISSUE TITLE
Provide the comparison table for the "青年诗歌" and the notes.

### ISSUE THREAD

**Issue by sw3rt** [cmeng-git/hymnchtv#6]
Notes:

1. 青年诗歌92 and 新歌颂咏34, same words, different melody. I wonder if it is corresponding.

2.
 青年诗歌 104, 148, 150, and 151 are divided into Version A and Version B. My format is as follows:
^ 0104: A这一生最美的祝福 #yb104
^ 0104: B家 #yb104
^ 0148: A奇异恩典 #yb148
^ 0148: B把爱送给你 #yb148
^ 0150: A又是新的一年 #yb150
^ 0150: B忘记背后 直奔标杆 #yb150
^ 0151: A当清晨时候 #yb151
^ 0151: B善美的事 #yb151

3. "附1" and "附2" do not have serial numbers, and I'm not sure how to match the format. They have not been added to this comparison table yet.

[TABLE.txt](https://github.com/user-attachments/files/17797112/TABLE.txt)

**Comment by sw3rt** [comment]
I crawled the text information from this site: [mygoodland](https://mygoodland.notion.site/1d1bab1894cb42cc8404faefde35e08c) and made some character formatting adjustments. I believe this comparison table is most likely accurate.

**Comment by cmeng-git** [comment]
Thanks for the effort to create the table. I will take a look for the implementation.

**Comment by cmeng-git** [comment]
The new release v2.5.0 has added support for "青年诗歌" .
To select the alternate hymnNo, enter the number e.g 148 and long press on  "青年" button.
There is quite a few "青年诗歌" hymn do not have the lyrics text for display. In this case just play the  "教唱". it will redirect and show the score for the hymn.

Actually Hymnch app uses only integer as reference for the selected hymnNo for display; The alternate hymn 104, 148, 150, 151 have actually reallocated to hymnNo 272, 273, 274, 275; you also enter these hymnNo to access the alternative. Please note, these numbers will be changed if there are more "青年诗歌"  hymns are added at a later time.

**Comment by sw3rt** [comment]
May the Lord remember your service and dedication.
